### ISSUE TITLE
Maybe write a command to auto download ciSQL jar file to package installed directory?

### ISSUE THREAD

**Issue by stardiviner** [plandes/icsql#2]
If it is possible, might can write a simple command to download jar file to `~/.emacs` directory or `~/.cisql` is great.

**Comment by plandes** [comment]
It [already does](https://github.com/plandes/icsql/blob/3d66e588556686563b8fb72d7654f840d88046c5/icsql.el#L133-L171).  Maybe I misunderstand--do you mean to a different directory so you can use it directly from the command line instead of Emacs?  For typical usage, you should be able to just follow the directions on the README on the main GitHub page.  Please let me know if there's anything not clear.

**Comment by stardiviner** [comment]
Aha, sorry I missed that. Thanks :smile:
